export const products=[
        {
            id:1,
            category:"women",
            image:"https://picsum.photos/300/200?random=1",
            details:"A good product for women.Women made it more beautiful",
            price:100,
            rating:4,
        },
        {
            id:2,
            category:"men",
            image:"https://picsum.photos/300/200?random=2",
            details:"A Specialize product which gives manly vibe. ",
            price:300,
            rating:3.5,
        },
        {
            id:3,
            category:"children",
            image:"https://picsum.photos/300/200?random=3",
            details:"specially design for children.The desginers gave it a new look.",
            price:200,
            rating:4.3,
        },
        {
            id:4,
            category:"accessories",
            image:"https://picsum.photos/300/200?random=4",
            details:"A product which has the most valuable accessories.",
            price:250,
            rating:3.8,
        },
        {
            id: 5, 
            category: "women", 
            image: "https://picsum.photos/300/200?random=5", 
            details:"specially made for women.like matches made in heaven.",
            price: 400, 
            rating: 4.5,
        },
        {
            id:6,
            category:"men",
            image:"https://picsum.photos/300/200?random=6",
            details:"special eddition for men.It gives a manly vibe dude.",
            price:320,
            rating:3,
        },
        {
            id:7,
            category:"children",
            image:"https://picsum.photos/300/200?random=7",
            details:"children who doesn't need motivation, cause it all depends on descipline.",
            price:200,
            rating:3,
        },
        {
            id:8,
            category:"accessories",
            image:"https://picsum.photos/300/200?random=8",
            details:"feels like livelyhood.Introduction to a new world.",
            price:100,
            rating:3,
        },
    ];