export const products=[
        {
            id:1,
            category:"women",
            image:"https://picsum.photos/300/200?random=1",
            details:"Women's Floral Cotton Kurti",
            price:100,
            rating:4,
        },
        {
            id:2,
            category:"men",
            image:"https://picsum.photos/300/200?random=2",
            details:"Men's Slim Fit Casual Shirt",
            price:300,
            rating:3.5,
        },
        {
            id:3,
            category:"children",
            image:"https://picsum.photos/300/200?random=3",
            details:"Kids Printed Cotton T-Shirt",
            price:200,
            rating:4.3,
        },
        {
            id:4,
            category:"accessories",
            image:"https://picsum.photos/300/200?random=4",
            details:"Classic Leather Wallet",
            price:250,
            rating:3.8,
        },
        {
            id: 5, 
            category: "women", 
            image: "https://picsum.photos/300/200?random=5", 
            details:"Women's Denim Jacket",
            price: 400, 
            rating: 4.5,
        },
        {
            id:6,
            category:"men",
            image:"https://picsum.photos/300/200?random=6",
            details:"Men's Hooded Sweatshirt",
            price:320,
            rating:3,
        },
        {
            id:7,
            category:"children",
            image:"https://picsum.photos/300/200?random=7",
            details:"Kids Sports Shoes",
            price:200,
            rating:3,
        },
        {
            id:8,
            category:"accessories",
            image:"https://picsum.photos/300/200?random=8",
            details:"Stylish Analog Wrist Watch",
            price:100,
            rating:3,
        },
    ];